# {{PROJECT_NAME}} — Project Rules

## #1 Rule: Read Before You Write

NEVER write code without first reading the existing code around it. Before creating or modifying any file, read a similar file in the target module or a similar module. Match exactly how things are structured, named, and wired.

**Consistency with existing code is more important than personal preference.**

## Overview

{{PROJECT_OVERVIEW}}

## Stack

- **Language**: {{LANGUAGE}}
- **Framework**: {{FRAMEWORK}}
- **Package manager**: {{PACKAGE_MANAGER}}
- **Database**: {{DATABASE}}

## Common commands

```bash
{{DEV_CMD}}      # start dev
{{TEST_CMD}}     # run tests
{{LINT_CMD}}     # lint
{{BUILD_CMD}}    # build
```

## Folder structure

```
{{FOLDER_STRUCTURE}}
```

## Naming conventions

{{NAMING_CONVENTIONS}}

## AI Knowledge Base

MANDATORY: Before performing any task, consult `ai/` in this order:

**Tier 1 — Always read at session start**

- `ai/_session-digest.md` — compact bootstrap (project, top conventions, last 3 ADRs, active follow-ups)

**Tier 2 — Read when task type matches**

- `ai/_convention-cheatsheet.md` — top ~20 conventions (code-write / refactor tasks)
- `ai/_decision-index.md` — ADR index (architectural decisions)
- `ai/business-domain.md` — domain glossary (feature / product work)
- `ai/business-flows.md` — operational flows (feature work)

**Tier 3 — Drill in on demand**

- `ai/README.md` — navigation + tier legend
- `ai/status.md` — current state + recent changes
- `ai/stack.md` — exact versions + scripts
- `ai/modules.md` — module inventory
- `ai/conventions.md` — full code conventions (after cheatsheet)
- `ai/architecture.md` — system shape + boundaries
- `ai/project-goals.md`, `ai/users-and-personas.md`, `ai/business-model.md`, `ai/competitive-context.md`, `ai/roadmap.md` — product context
- `ai/core/` — glossary, entities, invariants, architecture overview
- `ai/runtime/` — project quirks + domain anti-patterns
- `ai/patterns/` — reusable patterns
- `ai/decisions/` — ADRs (the "why")
- `ai/runbooks/` — step-by-step operational guides
- `ai/dynamic/` — session log, drift, learned patterns (working layer)

Update `ai/` when modules or patterns change. Derived files (`_session-digest`, `_decision-index`, `_convention-cheatsheet`) are regenerated by `knowledge-curator` / `/audit-knowledge` — edit their sources, not the derived bodies long-term.

## Automation

- `PostToolUse` hook runs lint on every edited source file — fix errors immediately, don't batch.
- `PreToolUse` hook blocks `.env`, lock files, and build-output edits.
- `SessionStart` hook prints branch, uncommitted count, and `ai/status.md` Recent Changes.

See `.claude/GUIDE.md` for the full surface.

## Anti-patterns

- No `any` types without justification.
- No `console.log` in committed code — use the project logger.
- No speculative abstractions for hypothetical future requirements.
- No `--no-verify` / bypassing hooks unless explicitly authorized.
- No mixing unrelated changes in one commit.

## Code style

{{CODE_STYLE}}
