#!/usr/bin/env bash
# _adapter-emit.sh — shared emitters for the TWO adapter lanes.
#
# Sourced by:
#   scripts/sync-to-global.sh    (GLOBAL lane — ~/.kimi, ~/.qwen, ~/.gemini, ~/.config/opencode, ~/.agents)
#   scripts/apply-adapter-sync.sh (PER-PROJECT lane — .kimi/, .qwen/, .gemini/, .opencode/, .agents/ in a repo)
#
# WHY THIS FILE EXISTS
#   The two lanes independently generated the same artifact shapes and drifted:
#   the global lane pinned /refine-prompt to OpenCode `plan` while the per-project
#   classifier gave it `build` (a write-command in a write-blocking mode), and the
#   global lane's Codex/Gemini generators sat unused one directory over while the
#   per-project lane emitted MISSING-AUTHOR for the identical shapes. One
#   definition per shape removes divergence by construction rather than by review.
#
# CONTRACT — every emitter here upholds three invariants, each learned from a
# shipped defect:
#   1. PREAMBLE. A ported command carries the EXECUTE NOW preamble or it loads as
#      inert reference: "user typed /skill:optimize, Kimi loaded the SKILL.md,
#      treated it as documentation, asked 'what now?'"
#      (templates/tool-adapters/kimi/adapter.md § Failure modes this dual-surface rule prevents).
#   2. MARKER. Every generated artifact carries GEN_MARK. --unlink recognises the
#      marker and nothing else; a surface generated without one cannot be
#      uninstalled and is invisible to scripts/verify-global-scope.sh check [4].
#   3. PARSEABLE FRONTMATTER. Descriptions are emitted through yaml_scalar(), never
#      raw. A description containing ": " (commands/delegate.md's anti-trigger list
#      does) turns an unquoted plain scalar into a YAML mapping error and the whole
#      frontmatter fails to parse in the target tool.
#
# bash 3.2 (macOS) compatible — no associative arrays, mapfile, or ${var,,}.

# Repo root, resolved from this file, not from the caller's cwd.
ADAPTER_EMIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ── Generation markers ──────────────────────────────────────────────────────
# Written into every generated artifact so --unlink can recognise ours.
GEN_MARK="source: refract/commands/"
# Pre-rename marker. The project was called claude-config before it became Refract;
# artifacts generated by those versions carry this string instead. --unlink MUST keep
# recognising it or an older install becomes un-uninstallable. Do not delete.
GEN_MARK_LEGACY="source: claude-config/commands/"

# True when a generated file carries the current OR the pre-rename marker.
is_generated() {
  grep -qF "$GEN_MARK" "$1" 2>/dev/null || grep -qF "$GEN_MARK_LEGACY" "$1" 2>/dev/null
}

# Source-path prefix recorded in each generated artifact's marker. The GLOBAL lane
# leaves the default, so its artifacts trace to this repo's commands/. The PER-PROJECT
# lane sets it to `source: .claude/commands/` so a project artifact traces to the
# project's own source of truth and is never mistaken for a global install.
ADAPTER_EMIT_MARK_PREFIX="${ADAPTER_EMIT_MARK_PREFIX:-$GEN_MARK}"
gen_marker() { printf '%s%s.md' "$ADAPTER_EMIT_MARK_PREFIX" "$1"; }

# ── Frontmatter validation ──────────────────────────────────────────────────
# Which engine frontmatter_parse_error() will use. Callers print this so a report
# never claims "valid YAML" when only the structural fallback ran.
# ADAPTER_EMIT_FM_ENGINE pins the engine (python-yaml | ruby-psych | structural-fallback).
# Set it to structural-fallback to exercise the no-dependency path on a box that HAS a
# parser — that path must be tested where it can be, not only where it is forced.
frontmatter_check_engine() {
  if [ -n "${ADAPTER_EMIT_FM_ENGINE:-}" ]; then printf '%s' "$ADAPTER_EMIT_FM_ENGINE"; return; fi
  if python3 -c 'import yaml' >/dev/null 2>&1; then printf 'python-yaml'; return; fi
  if command -v ruby >/dev/null 2>&1 && ruby -ryaml -e '' >/dev/null 2>&1; then printf 'ruby-psych'; return; fi
  printf 'structural-fallback'
}

# Print a one-line reason when $1's YAML frontmatter will NOT parse; print nothing
# when it parses (or when the file has no frontmatter at all). Never fails the shell.
#
# Why a real parse: the guard this replaces counted `---` fences and could not see the
# defect that actually shipped. commands/delegate.md's description contains
# `Anti-triggers (do NOT fire): a plain "implement X"` — an unquoted plain scalar with
# a colon-space, which YAML reads as a nested mapping. The source file itself fails to
# parse, and the fence-counting guard passed it.
#
# The structural fallback is NARROWER than a parse and is labelled as such by
# frontmatter_check_engine(). It flags that one shipped class plus a value opening with
# a YAML indicator character. It is not a substitute for a parser; it is what stays
# true with neither PyYAML nor Ruby on the box. A report that ran it must say so.
frontmatter_parse_error() {
  local f="$1"
  [ -f "$f" ] || return 0
  head -1 "$f" 2>/dev/null | grep -qx -- '---' || return 0
  # Unterminated opening fence: no closing --- anywhere after line 1.
  if ! awk 'NR>1 && /^---[[:space:]]*$/ {found=1; exit} END {exit !found}' "$f"; then
    printf 'opening --- never closed'
    return 0
  fi
  local fm; fm="$(awk 'NR==1 && /^---[[:space:]]*$/ {fm=1; next} fm==1 && /^---[[:space:]]*$/ {exit} fm==1 {print}' "$f")"
  local engine; engine="$(frontmatter_check_engine)"
  case "$engine" in
    python-yaml)
      printf '%s\n' "$fm" | python3 -c 'import sys, yaml
try:
    yaml.safe_load(sys.stdin.read())
except Exception as e:
    print(" ".join(str(e).split())[:160], end="")'
      ;;
    ruby-psych)
      printf '%s\n' "$fm" | ruby -ryaml -e 'begin
  YAML.safe_load($stdin.read)
rescue => e
  print e.message.split.join(" ")[0,160]
end'
      ;;
    *)
      printf '%s\n' "$fm" | awk '
        /^[A-Za-z_][A-Za-z0-9_.-]*:([[:space:]]|$)/ {
          v = $0; sub(/^[A-Za-z_][A-Za-z0-9_.-]*:[[:space:]]*/, "", v)
          if (v == "") next
          c = substr(v, 1, 1)
          if (c == "\"" || c == q) next          # quoted scalar: literal, always parses
          if (index(v, ": ") > 0) {
            print "unquoted plain scalar contains a colon-space (YAML reads it as a nested mapping) — single-quote the value"
            exit
          }
          if (c == "@" || c == "`" || c == "%") {
            print "unquoted plain scalar opens with the YAML indicator " c " — single-quote the value"
            exit
          }
        }
      ' q="'"
      ;;
  esac
  return 0
}


# ── Scalar encoders ─────────────────────────────────────────────────────────

# Emit $1 as a YAML scalar that always parses.
#
# Single-quoted YAML style is literal: `: `, `#`, `"`, `[`, `-`, `&`, `*`, `%` and a
# leading space all survive with no further escaping; the ONE escape is `'` → `''`.
# Unquoted was the bug — `Anti-triggers (do NOT fire): a plain "implement X"` in
# commands/delegate.md's description made Kimi, Codex, OpenCode and Qwen all emit
# frontmatter that fails to parse ("mapping values are not allowed in this context").
# Quoting at the EMITTER means no source description can break a generated artifact,
# whatever an author writes upstream.
yaml_scalar() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"
}

# Escape a string for embedding inside a TOML basic string.
toml_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

# Extract the one-line description from a command's frontmatter (raw, unquoted).
# Callers that put it in YAML MUST pass it through yaml_scalar first.
cmd_description() {
  local f="$1" d
  d="$(awk '/^description:/{sub(/^description:[[:space:]]*/,""); print; exit}' "$f")"
  [ -n "$d" ] && printf '%s' "$d" || printf 'Global command from Refract'
}

# ── Body emitter ────────────────────────────────────────────────────────────

# Print the command BODY (frontmatter stripped) prefixed with an EXECUTE-NOW
# preamble, so ported commands run instead of loading as inert reference.
#
#   $1 = command file
#   $2 = command name
#   $3 = args token for this tool ({{args}} | $ARGUMENTS | prose)
#   $4 = companion root (absolute) or "" — see § companion below
#
# TWO things this does that the old inline awk did not:
#
# (a) It strips the LEADING frontmatter block only. The old `/^---$/{fm++; next}`
#     deleted every line that was exactly `---` anywhere in the file, silently
#     removing 11 horizontal rules from the ported bodies of setup-project.md and
#     setup-project-adapters.md.
#
# (b) It rewrites repo-relative links. 41 links across 9 of the 15 commands point at
#     `../templates/…` and `../scripts/…`. Under Claude Code they resolve because
#     ~/.claude/{templates,scripts} mirror the repo. From ~/.kimi/skills/<n>/ or
#     ~/.qwen/commands/ they resolve to nothing — and the preamble has just told the
#     tool to execute a workflow whose mandatory reads 404. When a companion root is
#     given, the links are rewritten to it and the preamble names the absent-branch:
#     say the file was unreadable, never invent it.
#
# The preamble uses the HTML-comment-wrapped blockquote form documented at
# templates/tool-adapters/kimi/adapter.md § "The EXECUTE NOW preamble", which is also
# the form apply-adapter-sync.sh's strip_for_compare / extract_injected_preamble
# recognise — so a global artifact and a per-project one discount identically.
emit_exec_body() {
  local f="$1" name="$2" args_tok="$3" companion="${4:-}"
  printf -- '<!-- EXECUTE NOW preamble — generated by the Refract adapter lane. Do not edit this block. -->\n'
  printf -- '> **Direct-invoke directive (read this first when this document loads):**\n'
  printf -- '>\n'
  printf -- '> You are running the `/%s` workflow, ported from Claude Code so it works in this\n' "$name"
  printf -- '> tool when Claude Code is unavailable. Do NOT summarise the workflow below and ask\n'
  printf -- '> the user what to do — immediately begin executing it against the scope: %s\n' "$args_tok"
  printf -- '> (default: the whole repo if no scope is given). Drive to completion or to an\n'
  printf -- '> explicit halt; report results, not intent.\n'
  if [ -n "$companion" ]; then
    printf -- '>\n'
    printf -- '> Links below into `%s/` are this workflow companion files, symlinked\n' "$companion"
    printf -- '> from the Refract repo by the adapter sync. If one is absent, say in your output\n'
    printf -- '> that you could not read it and continue with what THIS document states — never\n'
    printf -- '> invent the contents of a file you could not open.\n'
  fi
  printf -- '<!-- /EXECUTE NOW preamble -->\n\n'
  awk -v comp="$companion" '
    # Literal (non-regex) replace — the companion path is a filesystem path and may
    # contain characters gsub would read as regex or as & backreferences.
    function lrep(s, from, to,   out, i) {
      out = ""
      while ((i = index(s, from)) > 0) { out = out substr(s, 1, i - 1) to; s = substr(s, i + length(from)) }
      return out s
    }
    NR == 1 && /^---[[:space:]]*$/ { fm = 1; next }   # opening fence
    fm == 1 && /^---[[:space:]]*$/ { fm = 2; next }   # closing fence
    fm == 1                        { next }          # frontmatter body
    {
      if (comp != "") {
        $0 = lrep($0, "](../templates/", "](" comp "/templates/")
        $0 = lrep($0, "](../scripts/",   "](" comp "/scripts/")
      }
      print
    }
  ' "$f"
}

# ── OpenCode agent-mode classifier (ONE definition, both lanes) ─────────────
#
# Classify an OpenCode command's `agent:` mode (build | plan) from the command
# SOURCE. Precedence:
#   1. an explicit `agent:` in the source frontmatter wins (author's declared choice);
#   2. `allowed-tools:` introspection — a pure-read toolset (no write/edit/shell) → plan,
#      anything that can write or shell → build;
#   3. conservative read-only NAME tokens (audit/scan/review/lint/… → plan);
#   4. default → build.
#
# The asymmetry is deliberate: mislabeling an action command `plan` BREAKS it (OpenCode's
# Plan mode blocks its writes/shell — the "I would do X, Y, Z" symptom), whereas an
# over-permissioned `build` on a read-only command is harmless. So `plan` is assigned only
# on a high-confidence read-only signal; everything else defaults to build.
#
# This was two functions. The global lane's hard-coded list pinned /refine-prompt to
# `plan` — and /refine-prompt writes ai/prompts/<YYYYMMDD>-<slug>.md, so the global lane
# put the one write-command it classified read-only into the mode that blocks its write.
# There is now one classifier; a name cannot be classified two ways again.
opencode_classify_command_agent() {
  local f="$1"
  # 1. explicit agent: in source frontmatter wins.
  local explicit
  explicit=$(awk '
    NR==1 && /^---[[:space:]]*$/ { fm=1; next }
    fm && /^---[[:space:]]*$/    { exit }
    fm && /^agent:[[:space:]]*/  { sub(/^agent:[[:space:]]*/,""); gsub(/[[:space:]]+$/,""); print; exit }
  ' "$f")
  if [ "$explicit" = "build" ] || [ "$explicit" = "plan" ]; then printf '%s' "$explicit"; return; fi
  # 2. allowed-tools introspection.
  local at
  at=$(awk '
    NR==1 && /^---[[:space:]]*$/        { fm=1; next }
    fm && /^---[[:space:]]*$/           { exit }
    fm && /^allowed-tools:[[:space:]]/  { print }
  ' "$f")
  if [ -n "$at" ]; then
    if printf '%s' "$at" | grep -qiE 'write|edit|multiedit|notebookedit|bash|execute'; then printf 'build'; else printf 'plan'; fi
    return
  fi
  # 3. conservative read-only name tokens.
  local base; base=$(basename "$f" .md)
  if printf '%s' "$base" | grep -qiE '(^|-)(audit|scan|review|lint|inspect|analyze|status|health|diff|trace|map)(-|$)|^check-|-check$'; then
    printf 'plan'; return
  fi
  # 4. default: action command.
  printf 'build'
}

# ── Per-tool artifact emitters (stdout) ────────────────────────────────────
# Each prints ONE complete generated file. Both lanes call these, so a shape fix
# lands in the global surface and in every project on the same commit.
#
#   $1 = source command file   $2 = command name   $3 = companion root or ""

# Kimi Code — ~/.kimi/skills/<name>/SKILL.md  |  .kimi/skills/<name>/SKILL.md
# Kimi documents no interpolation token for skills, so the scope is named in prose.
emit_command_skill() {
  local f="$1" name="$2" companion="${3:-}"
  printf -- '---\n'
  printf 'name: %s\n' "$name"
  printf 'description: %s\n' "$(yaml_scalar "$(cmd_description "$f")")"
  printf 'metadata:\n'
  printf '  %s\n' "$(gen_marker "$name")"
  printf -- '---\n\n'
  emit_exec_body "$f" "$name" 'the scope you name' "$companion"
}
emit_kimi_skill() { emit_command_skill "$@"; }

# Codex CLI — ~/.agents/skills/<name>/SKILL.md  |  .agents/skills/<name>/SKILL.md
# Open Agent Skills: `name` (required, [a-z0-9-]{1,64}) + `description` (required,
# 1-1024 chars); body is the workflow prose (codex/adapter.md § Agent Skills).
emit_codex_skill() { emit_command_skill "$@"; }

# Qwen Code — ~/.qwen/commands/<name>.md  |  .qwen/commands/<name>.md
# Frontmatter is `description:` ONLY (qwen/adapter.md § .qwen/commands/<name>.md);
# the Claude-only orchestrator fields are dropped, exactly as the OpenCode lane drops
# them. The args token is {{args}}, per the same section. The marker rides in a body
# HTML comment because the frontmatter has no key to carry it.
emit_qwen_command() {
  local f="$1" name="$2" companion="${3:-}"
  printf -- '---\n'
  printf 'description: %s\n' "$(yaml_scalar "$(cmd_description "$f")")"
  printf -- '---\n\n'
  printf -- '<!-- %s -->\n\n' "$(gen_marker "$name")"
  emit_exec_body "$f" "$name" '{{args}}' "$companion"
}

# OpenCode — ~/.config/opencode/commands/<name>.md  |  .opencode/commands/<name>.md
# Frontmatter is `description:` + `agent:` (+ optional model:/subtask:) per
# opencode/adapter.md § Commands. The generation marker is a BODY comment, not a
# frontmatter key: injecting a bare `source:` key into command frontmatter was the
# global lane emitting exactly the class of Claude-ism the per-project lane strips.
emit_opencode_command() {
  local f="$1" name="$2" companion="${3:-}"
  printf -- '---\n'
  printf 'description: %s\n' "$(yaml_scalar "$(cmd_description "$f")")"
  printf 'agent: %s\n' "$(opencode_classify_command_agent "$f")"
  printf -- '---\n\n'
  printf -- '<!-- %s -->\n\n' "$(gen_marker "$name")"
  emit_exec_body "$f" "$name" '$ARGUMENTS' "$companion"
}

# Gemini CLI — ~/.gemini/commands/<name>.toml  |  .gemini/commands/<name>.toml
# Literal multiline string ('''…''') — TOML processes NO escapes inside it, so
# backslashes and quotes in the command body survive verbatim. A body containing
# ''' would terminate the string early, so the emitter checks rather than asserts
# (the old code claimed bodies were "pre-verified" with nothing enforcing it) and
# falls back to the escape-processing basic form """…""" when it must.
emit_gemini_toml() {
  local f="$1" name="$2" companion="${3:-}" body
  body="$(emit_exec_body "$f" "$name" '{{args}}' "$companion")"
  printf '# %s\n' "$(gen_marker "$name")"
  printf 'description = "%s"\n\n' "$(toml_escape "$(cmd_description "$f")")"
  if printf '%s' "$body" | grep -qF "'''"; then
    # Basic multiline: escapes ARE processed, so backslash and " must be escaped.
    printf 'prompt = """\n'
    printf '%s' "$body" | sed 's/\\/\\\\/g; s/"""/\\"\\"\\"/g'
    printf '\n"""\n'
  else
    printf "prompt = '''\n"
    printf '%s' "$body"
    printf "\n'''\n"
  fi
}
