#!/usr/bin/env bash
# deep-codebase-scan.sh — full codebase inventory + semantic-questions checklist.
#
# M15 covered the .claude/ + ai/ artifact layer. M16 covers the actual codebase
# (src/, app/, lib/, etc.) so /setup-project --refresh / --refine / --enhance can't
# declare success after only touching surface-level setup files.
#
# Two outputs:
#   1. Mechanical inventory written to .claude/_codebase-scan.md — file counts,
#      directory tree, suffix patterns, manifest detection, framework markers.
#   2. Semantic-questions checklist appended — questions the LLM MUST answer
#      (base classes by extender count, drift between rules and code, modules
#      visible in code but missing from ai/modules.md, etc.). Empty answers
#      fail Phase 5 audit.
#
# Usage:
#   deep-codebase-scan.sh <target-repo>
#
# Output: <target>/.claude/_codebase-scan.md

set -euo pipefail
export LC_ALL=C

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <target-repo>" >&2
  exit 2
fi

TARGET="$1"
[[ -d "$TARGET" ]] || { echo "ERR: target not found: $TARGET" >&2; exit 1; }

REPORT="$TARGET/.claude/_codebase-scan.md"
mkdir -p "$(dirname "$REPORT")"

# ---------- Helpers ----------
count_files() {
  local pattern="$1"
  find "$TARGET" -type f -name "$pattern" \
    -not -path "*/node_modules/*" \
    -not -path "*/.git/*" \
    -not -path "*/dist/*" \
    -not -path "*/build/*" \
    -not -path "*/.next/*" \
    -not -path "*/__pycache__/*" \
    -not -path "*/.venv/*" \
    -not -path "*/vendor/*" \
    -not -path "*/.claude/backups/*" \
    2>/dev/null | wc -l | tr -d ' '
}

ls_dirs() {
  local maxdepth="$1"
  find "$TARGET" -mindepth 1 -maxdepth "$maxdepth" -type d \
    -not -path "*/node_modules*" \
    -not -path "*/.git*" \
    -not -path "*/dist*" \
    -not -path "*/build*" \
    -not -path "*/.next*" \
    -not -path "*/__pycache__*" \
    -not -path "*/.venv*" \
    -not -path "*/vendor*" \
    -not -path "*/.claude/backups*" \
    2>/dev/null | sort
}

# ---------- Build report ----------
{
  printf '# Codebase deep scan — %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'Target: `%s`\n\n' "$TARGET"
  printf 'Generated by: scripts/deep-codebase-scan.sh\n\n'
  printf '> **MANDATORY for REFRESH / REFINE / ENHANCE.** Phase 0.0 runs this script. Phase 4.6 anchors generated content to its findings. Phase 5 audit FAILS the run if any **semantic question below is left unanswered (`<TBD>`)** — those questions require LLM judgment that the script cannot do mechanically, but Phase 4 cannot proceed without the answers.\n\n'
  printf -- '---\n\n'

  # ----- Section 1: File count by language -----
  printf '## 1. File count by language (mechanical)\n\n'
  printf '```\n'
  for ext in ts tsx js jsx vue svelte py rb php java kt swift go rs cs cpp c h hpp scala ex exs erl elm hs ml lua sh sql graphql proto md yaml yml json toml; do
    n=$(count_files "*.$ext")
    [[ "$n" -gt 0 ]] && printf '%-8s %d\n' "$ext" "$n"
  done
  printf '```\n\n'

  # ----- Section 2: Top-level directories -----
  printf '## 2. Top-level directories (depth 2)\n\n'
  printf '```\n'
  ls_dirs 2 | head -40 | sed "s|$TARGET/||"
  printf '```\n\n'

  # ----- Section 3: Manifest / config files detected -----
  printf '## 3. Manifests + framework markers\n\n'
  printf '```\n'
  for f in package.json package-lock.json pnpm-lock.yaml yarn.lock bun.lockb \
           pyproject.toml requirements.txt Pipfile poetry.lock setup.py \
           Gemfile Gemfile.lock composer.json composer.lock \
           go.mod go.sum Cargo.toml Cargo.lock \
           pom.xml build.gradle build.gradle.kts settings.gradle \
           tsconfig.json next.config.js next.config.mjs nuxt.config.ts \
           vite.config.ts vite.config.js webpack.config.js rollup.config.js \
           tailwind.config.js tailwind.config.ts postcss.config.js \
           .eslintrc.json .eslintrc.js eslint.config.js \
           jest.config.js jest.config.ts vitest.config.ts \
           playwright.config.ts cypress.config.ts \
           Dockerfile docker-compose.yml docker-compose.yaml \
           .gitignore .env.example; do
    if find "$TARGET" -maxdepth 3 -name "$f" -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | head -1 | grep -q .; then
      paths=$(find "$TARGET" -maxdepth 3 -name "$f" -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | head -3 | sed "s|$TARGET/||")
      printf '%-30s %s\n' "$f" "$paths"
    fi
  done
  printf '```\n\n'

  # ----- Section 4: Suffix patterns (file-naming convention detection) -----
  printf '## 4. Suffix patterns (file-naming conventions visible)\n\n'
  printf 'Counts files matching common architectural suffixes:\n\n'
  printf '```\n'
  for suffix in service controller repository repo entity model dto schema view module hook composable provider middleware guard interceptor handler validator factory mapper builder helper util store reducer slice action page layout component widget screen route api migration test spec; do
    for ext in ts tsx js jsx py rb go; do
      n=$(find "$TARGET" -type f -name "*.$suffix.$ext" \
        -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | wc -l | tr -d ' ')
      [[ "$n" -ge 3 ]] && printf '%-25s %d files\n' "*.$suffix.$ext" "$n"
    done
  done
  printf '```\n\n'

  # ----- Section 5: Source LOC -----
  printf '## 5. Lines of code (excluding comments + tests)\n\n'
  printf 'Approximate (counts all lines incl. blank/comments — finer counts need cloc):\n\n'
  printf '```\n'
  for ext in ts tsx js jsx py rb php java kt swift go rs; do
    total_lines=$(find "$TARGET" -type f -name "*.$ext" \
      -not -path "*/node_modules/*" -not -path "*/.git/*" \
      -not -path "*/dist/*" -not -path "*/build/*" \
      -not -path "*/.next/*" -not -path "*/__pycache__/*" \
      -not -path "*/.venv/*" -not -path "*/vendor/*" \
      -not -path "*test*" -not -path "*spec*" \
      2>/dev/null -exec cat {} + | wc -l | tr -d ' ')
    [[ "$total_lines" -gt 0 ]] && printf '%-8s %s lines\n' "$ext" "$total_lines"
  done
  printf '```\n\n'

  # ----- Section 6: Patterns to grep (potential base classes / repeated structures) -----
  printf '## 6. Pattern grep — potential base classes (3+ extenders)\n\n'
  printf '```\n'
  # TS/JS class extenders. `|| true` keeps the pipeline alive under pipefail
  # when grep finds nothing.
  { grep -rEo "class [A-Z][A-Za-z0-9_]+ extends [A-Z][A-Za-z0-9_]+" "$TARGET" \
    --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
    --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude-dir=build \
    2>/dev/null || true; } | sed -E 's/.*extends //' | sort | uniq -c | sort -rn | awk '$1 >= 3' | head -10
  { grep -rEo "class [A-Z][A-Za-z0-9_]+\([A-Z][A-Za-z0-9_]+" "$TARGET" \
    --include="*.py" \
    --exclude-dir=__pycache__ --exclude-dir=.venv --exclude-dir=.git \
    2>/dev/null || true; } | sed -E 's/.*\(//' | sort | uniq -c | sort -rn | awk '$1 >= 3' | head -10
  printf '```\n\n'

  # ----- Section 7: Existing .claude/+ai/ summary (cross-reference for drift detection) -----
  printf '## 7. Setup artifact summary (cross-reference)\n\n'
  printf '```\n'
  for path in CLAUDE.md AGENTS.md ai/conventions.md ai/architecture.md ai/modules.md ai/business-domain.md ai/status.md; do
    if [[ -f "$TARGET/$path" ]]; then
      printf '%-30s %d lines\n' "$path" "$(wc -l < "$TARGET/$path" | tr -d ' ')"
    fi
  done
  for kind in agents commands skills rules; do
    if [[ -d "$TARGET/.claude/$kind" ]]; then
      n=$(find "$TARGET/.claude/$kind" -maxdepth 1 -name '*.md' -not -name '_*' 2>/dev/null | wc -l | tr -d ' ')
      printf '%-30s %d files\n' ".claude/$kind/" "$n"
    fi
  done
  if [[ -d "$TARGET/ai/patterns" ]]; then
    n=$(find "$TARGET/ai/patterns" -maxdepth 1 -name '*.md' -not -name '_*' -not -name 'README*' 2>/dev/null | wc -l | tr -d ' ')
    printf '%-30s %d files\n' "ai/patterns/" "$n"
  fi
  if [[ -d "$TARGET/ai/decisions" ]]; then
    n=$(find "$TARGET/ai/decisions" -maxdepth 1 -name '*.md' -not -name '_*' -not -name 'README*' -not -name '_template*' 2>/dev/null | wc -l | tr -d ' ')
    printf '%-30s %d ADRs\n' "ai/decisions/" "$n"
  fi
  printf '```\n\n'

  # ----- Section 8-15: Semantic questions (LLM must answer; empty = Phase 5 fails) -----
  cat <<'PROSE'
---

## 8. Module map — what's actually in the code (LLM must fill)

> List top-level features / bounded contexts visible in the codebase. Cite directory paths. For each: 1-line responsibility. Cross-reference with `ai/modules.md` — flag anything in code but missing from the map (and vice versa).

<TBD>

## 9. Architecture pattern detected (LLM must fill)

> What architectural style is the code actually following (clean / hexagonal / layered / MVC / mod-mono / event-driven)? Cite the directory boundaries that prove it (e.g., `core/` imports nothing from framework lib X). Compare to `ai/architecture.md` declaration — flag drift.

<TBD>

## 10. Conventions visible in code (LLM must fill)

> Top 10 conventions visible in the code (file naming, folder structure, import style, error handling, validation, testing, logging, etc.). Cite real file paths as evidence. Compare to `ai/conventions.md` — flag rules in convention file that the code does NOT follow, AND code patterns that aren't documented.

<TBD>

## 11. Patterns repeated 3+ times (LLM must fill)

> Patterns appearing 3+ times that should be in `ai/patterns/<name>.md` but aren't. Examples: "every list endpoint paginates the same way", "every form uses `<schema>.parse(input)` for validation", "every service emits a domain event on success". Cite file paths.

<TBD>

## 12. Decisions implicit in code (LLM must fill)

> Architectural choices visible in the code but NOT documented as ADRs. Examples: "chose Drizzle over Prisma" (verifiable from imports), "auth via NextAuth not Clerk" (verifiable from session-handling code). Each: 1-2 line rationale + which file shows the decision. Phase 4 may propose ADRs for the most important.

<TBD>

## 13. Drift between rules and code (LLM must fill)

> For each rule in `.claude/rules/*.md`, sample-check against the code. Examples: rule says "always use parameterized queries" — does the code? rule says "no any types" — grep `: any` and report count. Flag rules the code violates AND rules that are too vague to enforce.

<TBD>

## 14. Stale references in setup (LLM must fill)

> References to files / classes / paths in `ai/*` and `.claude/*.md` that no longer exist in the code. Examples: `ai/architecture.md` cites `src/legacy/auth.ts` but it's been removed; an agent's pre-flight references a pattern file that was deleted.

<TBD>

## 15. Recommended structural improvements (LLM must fill)

> Concrete proposals at the system level — NOT minor isolated changes. Format per item:
>
> - **What**: <one-line description>
> - **Why**: <evidence from sections 8-14>
> - **Where**: <files / modules affected>
> - **Effort**: <small/medium/large>
> - **Risk**: <low/medium/high>
>
> Examples that QUALIFY as structural:
> - "Extract `services/` from `controllers/` — 4 controllers contain inline business logic that should move to a service layer per architecture style declared in ai/architecture.md."
> - "Add `ai/patterns/parallel-io.md` — found 8 places where independent awaits run sequentially; document the parallel pattern + cite the project's helper at `lib/concurrent.ts`."
> - "Update `ai/conventions.md` § Naming — current rule says PascalCase but 12 files use kebab-case; either update the rule or rename the files."
>
> Examples that do NOT qualify (these are minor / isolated):
> - "Add a comment to function X."
> - "Rename one file."
> - "Update a single import."

<TBD>
PROSE

  printf '\n---\n\n'
  printf '## Phase 5 audit gates this report\n\n'
  printf 'Phase 5 (verify) FAILS the run if:\n\n'
  printf -- '- Any of sections 8-15 is left as `<TBD>`.\n'
  printf -- '- Section 15 contains < 3 structural recommendations on a non-trivial codebase (≥1000 LOC).\n'
  printf -- '- Section 15 recommendations are minor / isolated (rejected per the qualifying examples above).\n\n'
  printf 'These gates exist because the historic bug was: refresh / refine / enhance ran shallow — touched ≤5 surface files, never compared rules to code, never proposed structural changes. M16 makes that pattern impossible to ship as "complete."\n'
} > "$REPORT"

echo "Codebase scan written: $REPORT"
echo "Mechanical sections (1-7) auto-filled. LLM must fill sections 8-15."
exit 0
