#!/usr/bin/env bash
# lint-orphan-templates.sh — a shipped `.tpl` must have something that renders it.
#
# WHY. `templates/repo-baseline/CLAUDE.md.tpl` sat in the baseline from the initial commit,
# was skipped by apply-baseline-sync.sh (`*.tpl` are "templated by the agent at scaffold time"),
# carried two entries in .baseline-hashes so it was drift-checked forever — and was named by
# NOTHING. `grep -rn CLAUDE.md.tpl` over templates/, commands/ and docs/ returned only that skip
# comment. Meanwhile the CLAUDE.md a project actually receives is generated by
# phase-4-templates.md § 4.7b, which is why a real installed project carries sections the .tpl
# does not contain at all.
#
# The cost is not the dead bytes. It is that an edit to the orphan LOOKS like it reached projects:
# the file is in the baseline, it is hashed, `gen-baseline-hashes.py --check` goes green, and
# nothing anywhere says the change landed nowhere. That happened on this branch, to instructions
# whose entire purpose was to reach the agent.
#
# THE CHECK. Every `*.tpl` under templates/*-baseline/ must be named by at least one file under
# templates/phases/, commands/, or scripts/ — the three places that could render it. The skip
# comment in apply-baseline-sync.sh does not count as a consumer: it is what DECLINES to copy it.
#
# Usage: lint-orphan-templates.sh [--quiet]
# Exit:  0 every .tpl has a renderer / 1 one does not

set -uo pipefail
export LC_ALL=C

_ss="${BASH_SOURCE[0]}"
while [ -L "$_ss" ]; do _sd="$(cd -P "$(dirname "$_ss")" && pwd)"; _ss="$(readlink "$_ss")"; case "$_ss" in /*) ;; *) _ss="$_sd/$_ss" ;; esac; done
REPO_ROOT="$(cd -P "$(dirname "$_ss")/.." && pwd)"; unset _ss _sd
cd "$REPO_ROOT" || exit 1

QUIET=0
[ "${1:-}" = "--quiet" ] && QUIET=1
say() { [ $QUIET -eq 0 ] && echo "$@"; return 0; }

echo "=== lint-orphan-templates ==="
say ""

TPLS=$(find templates -type f -name '*.tpl' 2>/dev/null | sort)
if [ -z "$TPLS" ]; then
  echo "PASS  no .tpl files to check."
  exit 0
fi

fails=0; checked=0
for t in $TPLS; do
  checked=$((checked+1))
  base=$(basename "$t")
  # Search the renderers only. Two exclusions, both because a mention there is not a rendering:
  # apply-baseline-sync.sh, whose single mention is the line that SKIPS these files; and this
  # script, whose header names the orphan it was written for — counting either would let a file
  # certify itself. (Caught by this gate's first run, which reported the orphan as "rendered by:
  # scripts/lint-orphan-templates.sh".)
  hits=$(grep -rln --include='*.md' --include='*.sh' --include='*.py' "$base" \
           templates/phases commands scripts 2>/dev/null \
         | grep -v 'apply-baseline-sync\.sh' \
         | grep -v 'lint-orphan-templates\.sh' \
         | grep -v "^$t$" || true)
  if [ -n "$hits" ]; then
    say "  ok    $t"
    say "        rendered by: $(printf '%s' "$hits" | tr '\n' ' ')"
  else
    echo "FAIL  $t is shipped and hashed, but no phase, command or script names it."
    echo "      Either wire a renderer, or delete it — a hashed orphan makes an edit to it"
    echo "      look like it reached projects when it reached nothing."
    fails=$((fails+1))
  fi
done

say ""
echo "reach: $checked .tpl file(s) checked"
if [ $fails -gt 0 ]; then
  echo ""
  echo "FAIL  $fails orphaned template(s)."
  exit 1
fi
echo "PASS  every shipped template has something that renders it."
exit 0
