#!/usr/bin/env bash
# pack-coverage-scan.sh — deterministic shell-side scan of pack content vs target.
#
# Solves the M11 bug: the agent (LLM running /setup-project) was reading prose
# rules about scanning pack directories and skipping the actual scan. This
# script does the scan in shell (no LLM judgment), writes a structured report,
# and Phase 4.0 / Phase 5 require the agent to consume it.
#
# Usage:
#   pack-coverage-scan.sh <target-repo> [pack1 pack2 ...]
#
# If no packs listed, scans every selected pack from <target>/.claude/codebase-profile.md
# (line "tracks_selected: ..."). Falls back to scanning all packs if profile missing.
#
# Output: <target>/.claude/_pack-coverage-report.md (structured markdown).
# Exit codes: 0 = report written; 1 = target missing; 2 = usage error.
#
# Properties:
# - Deterministic. Same input → same output.
# - Idempotent. Re-running overwrites the report (it's derived).
# - Read-only on the target's actual artifacts. Only writes the report.

set -euo pipefail
export LC_ALL=C

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKS_ROOT="$REPO_ROOT/templates/packs"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <target-repo> [pack1 pack2 ...]" >&2
  exit 2
fi

TARGET="$1"; shift
[[ -d "$TARGET" ]] || { echo "ERR: target repo not found: $TARGET" >&2; exit 1; }

REPORT="$TARGET/.claude/_pack-coverage-report.md"
mkdir -p "$(dirname "$REPORT")"

# Determine packs to scan
PACKS=("$@")
if [[ ${#PACKS[@]} -eq 0 ]]; then
  if [[ -f "$TARGET/.claude/codebase-profile.md" ]]; then
    while IFS= read -r p; do
      [[ -n "$p" ]] && PACKS+=("$p")
    done < <(grep -E '^[[:space:]]*-?[[:space:]]*track:' "$TARGET/.claude/codebase-profile.md" 2>/dev/null \
             | sed -E 's/.*track:[[:space:]]+([a-z0-9-]+).*/\1/' | sort -u)
  fi
fi
if [[ ${#PACKS[@]} -eq 0 ]]; then
  # Try find first; some sandboxes restrict find traversal even when ls works,
  # so fall back to a bash glob if find returns nothing.
  while IFS= read -r d; do
    name="$(basename "$d")"
    [[ "$name" == _* ]] && continue
    PACKS+=("$name")
  done < <(find "$PACKS_ROOT" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)
  if [[ ${#PACKS[@]} -eq 0 ]]; then
    for d in "$PACKS_ROOT"/*/; do
      [[ -d "$d" ]] || continue
      name="$(basename "$d")"
      [[ "$name" == _* ]] && continue
      [[ "$name" == "*" ]] && continue
      PACKS+=("$name")
    done
  fi
fi
# bash 3.2 (macOS default) treats `${arr[*]}` on an empty array as unbound under
# set -u — guard the trace line so it never crashes the preflight.
if [[ ${#PACKS[@]} -gt 0 ]]; then
  echo "Scanning packs: ${PACKS[*]}" >&2
else
  echo "Scanning packs: (none — neither codebase-profile track: lines nor $PACKS_ROOT scan yielded packs)" >&2
  echo "ERR: cannot proceed with zero packs. Pass packs as args, or check $PACKS_ROOT exists and is readable." >&2
  exit 1
fi

# Per-kind target dir resolution (per pack.md emit conventions)
target_dir_for_kind() {
  local kind="$1"
  case "$kind" in
    commands)    echo "$TARGET/.claude/commands" ;;
    agents)      echo "$TARGET/.claude/agents" ;;
    skills)      echo "$TARGET/.claude/skills" ;;
    rules)       echo "$TARGET/.claude/rules" ;;
    ai-patterns) echo "$TARGET/ai/patterns" ;;
    *)           echo "$TARGET/.claude/$kind" ;;
  esac
}

# ---------- Build report ----------
{
  printf '# Pack coverage scan — %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'Target: `%s`\n\n' "$TARGET"
  printf 'Generated by: scripts/pack-coverage-scan.sh\n\n'
  printf '> **THIS REPORT IS THE SOURCE OF TRUTH** for "what should be in the target." The agent MUST read it before declaring `idempotent — no work to do`. Phase 5 audit FAILS the run if any pack shows missing files that were not addressed.\n\n'
  printf -- '---\n\n'

  total_missing=0
  for pack in "${PACKS[@]}"; do
    pack_dir="$PACKS_ROOT/$pack"
    [[ -d "$pack_dir" ]] || { printf '## %s\n\n  ERR — pack source not found at %s\n\n' "$pack" "$pack_dir"; continue; }

    printf '## %s\n\n' "$pack"
    pack_missing=0

    for kind in commands agents skills rules ai-patterns; do
      kind_dir="$pack_dir/$kind"
      [[ -d "$kind_dir" ]] || continue

      tgt_dir="$(target_dir_for_kind "$kind")"
      missing=()
      present=()

      while IFS= read -r f; do
        base="$(basename "$f")"
        [[ "$base" == _* ]] && continue
        if [[ -f "$tgt_dir/$base" ]]; then
          present+=("$base")
        else
          missing+=("$base")
        fi
      done < <(find "$kind_dir" -maxdepth 1 -name '*.md' -not -name '_*' | sort)

      total=$(( ${#missing[@]} + ${#present[@]} ))
      [[ $total -eq 0 ]] && continue

      printf '### %s (%d total)\n\n' "$kind" "$total"

      if [[ ${#missing[@]} -gt 0 ]]; then
        printf '**Missing — Phase 4.2 must copy or apply merge matrix to:**\n\n'
        for m in "${missing[@]}"; do
          printf -- '- `%s/%s` ← from `%s/%s/%s`\n' "${tgt_dir#$TARGET/}" "$m" "templates/packs/$pack" "$kind" "$m"
        done
        printf '\n'
        pack_missing=$(( pack_missing + ${#missing[@]} ))
      fi

      if [[ ${#present[@]} -gt 0 ]]; then
        printf '**Present — re-evaluate via Appendix C merge matrix (size ratio: ours / theirs):**\n\n'
        for p in "${present[@]}"; do
          src_size=$(wc -l < "$kind_dir/$p" | tr -d ' ')
          tgt_size=$(wc -l < "$tgt_dir/$p" | tr -d ' ')
          printf -- '- `%s/%s` (target: %d lines, pack: %d lines)\n' "${tgt_dir#$TARGET/}" "$p" "$tgt_size" "$src_size"
        done
        printf '\n'
      fi
    done

    if [[ "$pack_missing" -eq 0 ]]; then
      printf 'pack coverage: COMPLETE (all files present in target — re-evaluate via merge matrix only)\n\n'
    else
      printf 'pack coverage: **%d files missing** — Phase 4.2 must address.\n\n' "$pack_missing"
      total_missing=$(( total_missing + pack_missing ))
    fi
    printf -- '---\n\n'
  done

  printf '## Summary\n\n'
  printf 'Packs scanned: %d\n' "${#PACKS[@]}"
  printf 'Total missing files across all packs: **%d**\n\n' "$total_missing"

  if [[ "$total_missing" -eq 0 ]]; then
    printf 'Coverage: COMPLETE. The agent MAY conclude `no Phase-4.2 copy work` IF AND ONLY IF other gates also pass (drift, prompt delta, schema validation).\n'
  else
    printf '⚠ Coverage: INCOMPLETE. The agent MUST address every "Missing" file above before declaring "no work to do." Re-running `/setup-project --include=<pack>` is REQUIRED to apply.\n'
  fi
} > "$REPORT"

echo "Report written: $REPORT"
echo "Total missing files: $total_missing"
exit 0
