#!/usr/bin/env bash
# refresh-extract-checklist.sh — deterministic shell-side check of REFRESH-mode extraction depth.
#
# Solves the M15 second bug: REFRESH was shallow. The agent backed up + version-stamped + a few
# derived files and called it done, skipping the deep "read existing setup, extract knowledge,
# merge with re-detection" work that REFRESH's contract requires.
#
# This script INVENTORIES what's in the target's existing setup BEFORE Phase 4 regenerates,
# writes a structured report at <target>/.claude/_refresh-extract.md with sections that MUST
# be filled by Phase 0.2. Phase 5 audit fails the run if any required section is empty.
#
# Usage:
#   refresh-extract-checklist.sh <target-repo>
#
# Output: <target>/.claude/_refresh-extract.md

set -euo pipefail
export LC_ALL=C

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <target-repo> [--force]" >&2
  exit 2
fi

TARGET="$1"; shift || true
FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -d "$TARGET" ]] || { echo "ERR: target not found: $TARGET" >&2; exit 1; }

REPORT="$TARGET/.claude/_refresh-extract.md"
mkdir -p "$(dirname "$REPORT")"

# Idempotency: if report exists with any LLM-filled section (i.e., contains
# non-trivial content under any "Phase 0.2 must fill" heading), skip overwrite
# unless --force is passed. Re-running this script wiping LLM-filled sections
# was the bug that caused the agent to re-fill the same content every preflight.
if [[ -f "$REPORT" && "$FORCE" -eq 0 ]]; then
  # Count <TBD> markers in LLM sections (sections 2-9). If <8, the report has
  # been at least partially filled — preserve it. Note: grep -c exits 1 when 0
  # matches, so we must not pipe through `|| echo 0` (that would concatenate
  # grep's "0" stdout with the fallback "0", producing "0\n0" — invalid integer).
  tbd_count=$(grep -c '^<TBD>$' "$REPORT" 2>/dev/null) || tbd_count=0
  if [[ "$tbd_count" -lt 8 ]]; then
    echo "Extract checklist preserved (already filled): $REPORT"
    echo "  ($tbd_count of 8 LLM-fill sections still <TBD>; pass --force to regenerate fresh template)"
    exit 0
  fi
fi

# Helpers — count files, get sizes.
# `enum` is the single dual-form enumerator: flat `<name>.md` (depth 1) plus Agent Skills
# dir-form `<name>/SKILL.md` (depth 2). Every helper below routes through it so an inventory
# of a skills/ dir on the Agent Skills convention cannot silently report 0 files.
enum() {
  [[ -d "$1" ]] || return 0
  { find "$1" -maxdepth 1 -name '*.md' -not -name '_*' 2>/dev/null
    find "$1" -mindepth 2 -maxdepth 2 -name 'SKILL.md' -not -path "$1/_*" 2>/dev/null
  } | sort
}
count() { enum "$1" | wc -l | tr -d ' '; }
total_lines() {
  local t=0 f
  while IFS= read -r f; do t=$(( t + $(wc -l < "$f" | tr -d ' ') )); done < <(enum "$1")
  echo "$t"
}
list_files() {
  enum "$1" | while IFS= read -r f; do
    echo "  - ${f#"$1"/} ($(wc -l < "$f" | tr -d ' ') lines)"
  done
}

{
  printf '# REFRESH extract checklist — %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'Target: `%s`\n\n' "$TARGET"
  printf 'Generated by: scripts/refresh-extract-checklist.sh\n\n'
  printf '> **MANDATORY for REFRESH/REFINE.** Phase 0.2 fills the prose sections below; Phase 5 audit FAILS the run if any required section is left empty (`<TBD>` / `<EMPTY>`). This file is the contract preventing surface-level "REFRESH = backup + version stamp + go" failures.\n\n'
  printf -- '---\n\n'

  # ---------- Section 1: Existing artifact inventory (auto-filled by this script) ----------
  printf '## 1. Existing artifact inventory (auto-filled by this script)\n\n'
  printf 'These counts are mechanically derived. The agent reads them; does not edit.\n\n'

  printf '### .claude/\n\n'
  for kind in agents commands skills rules hooks; do
    dir="$TARGET/.claude/$kind"
    if [[ -d "$dir" ]]; then
      n=$(count "$dir")
      printf -- '- **%s/**: %d files\n' "$kind" "$n"
      list_files "$dir"
    else
      printf -- '- **%s/**: not present\n' "$kind"
    fi
  done

  printf '\n### ai/\n\n'
  for f in CLAUDE.md AGENTS.md; do
    if [[ -f "$TARGET/$f" ]]; then
      printf -- '- **%s**: %d lines\n' "$f" "$(wc -l < "$TARGET/$f" | tr -d ' ')"
    else
      printf -- '- **%s**: not present\n' "$f"
    fi
  done
  for f in conventions.md architecture.md status.md modules.md business-domain.md project-goals.md; do
    if [[ -f "$TARGET/ai/$f" ]]; then
      printf -- '- **ai/%s**: %d lines\n' "$f" "$(wc -l < "$TARGET/ai/$f" | tr -d ' ')"
    fi
  done
  if [[ -d "$TARGET/ai/decisions" ]]; then
    n=$(find "$TARGET/ai/decisions" -name '*.md' -not -name '_*' -not -name 'README*' 2>/dev/null | wc -l | tr -d ' ')
    printf -- '- **ai/decisions/**: %d ADRs\n' "$n"
    find "$TARGET/ai/decisions" -name '*.md' -not -name '_*' -not -name 'README*' 2>/dev/null | sort | head -20 | while IFS= read -r adr; do
      printf '    - `%s`\n' "$(basename "$adr")"
    done
  fi
  for kind in patterns runbooks runtime audits dynamic; do
    dir="$TARGET/ai/$kind"
    if [[ -d "$dir" ]]; then
      n=$(find "$dir" -name '*.md' -not -name '_*' -not -name 'README*' 2>/dev/null | wc -l | tr -d ' ')
      printf -- '- **ai/%s/**: %d files\n' "$kind" "$n"
    fi
  done
  if [[ -d "$TARGET/ai/failures" ]]; then
    n=$(find "$TARGET/ai/failures" -name '*.md' -not -name '_*' 2>/dev/null | wc -l | tr -d ' ')
    printf -- '- **ai/failures/**: %d failure entries\n' "$n"
  fi

  printf '\n---\n\n'

  # ---------- Section 2-9: Required prose sections (Phase 0.2 fills) ----------
  cat <<'PROSE'
## 2. ADRs preserved (Phase 0.2 must fill)

> List every ADR by ID + title + one-line summary. ADRs are append-only; they will NOT be regenerated. Empty list when there are zero ADRs.

<TBD>

## 3. Validated user corrections (Phase 0.2 must fill)

> User-given truth that is NOT in the codebase but must be preserved. Example: "Tenant scope auto-applied via AsyncLocalStorage — never accept tenant_id in request body." Source: existing rules, comments, ADRs, dynamic/feedback-learned.md.

<TBD>

## 4. Project intent (Phase 0.2 must fill)

> Facts the codebase doesn't encode but the team relies on. Goals, target users, business priorities, constraints (compliance, deadline, scale). Extracted from `ai/project-goals.md`, `ai/business-domain.md`, `ai/users-and-personas.md`, `ai/competitive-context.md`.

<TBD>

## 5. Custom rules (Phase 0.2 must fill)

> Rules the project authored that are NOT in the universal pack. Each: file path + 1-line purpose. Phase 4 wires these BACK into post-baseline overrides.

<TBD>

## 6. Custom agents/skills/commands (Phase 0.2 must fill)

> Agents/skills/commands the project authored that the pack doesn't have OR that the project specialized beyond pack equivalent. Per item: name + role + replaces/specializes which generic. Used by Phase 4.2 merge matrix to SKIP-with-redirect generic pack equivalents.

<TBD>

## 7. Architecture decisions implicit in code (Phase 0.2 must fill)

> Patterns visible in code but NOT documented in ADRs. Layering, framework choice, data-access style, error handling pattern. Phase 4.6 anchors generated content to these.

<TBD>

## 8. Detected stack + version (Phase 0.2 must fill)

> Languages, frameworks, ORMs, test runners, build tools — with versions. From manifests, lock files, config files. Used by Phase 4.6 to cite the right APIs.

<TBD>

## 9. Migration / V1↔V2 mapping (only if migration in scope)

> If `--include=migration` was set OR Phase 2 detected V1+V2 layout: V1 root path, V2 root path, cutover mechanism, current ledger state. Phase 4.6 anchors migration artifacts to these.

<TBD>
PROSE

  printf '\n---\n\n'
  printf '## Phase 5 audit gates this report\n\n'
  printf 'Phase 5 (verify) FAILS the run if:\n\n'
  printf -- '- Any of sections 2-8 is left as `<TBD>` (REFRESH default mode).\n'
  printf -- '- Section 9 is `<TBD>` AND `--include=migration` was set OR migration_layout_detected.\n'
  printf -- '- Section 1 (auto-filled) shows ≥10 files preserved AND sections 5/6 are empty (impossible — files exist but no extraction performed).\n\n'
  printf 'These gates exist because the historic REFRESH bug was exactly this: the agent ran "backup + version-stamp + a few derived files" and reported success, leaving the extract step at zero-effort.\n'
} > "$REPORT"

echo "Extract checklist written: $REPORT"
echo "Phase 0.2 must now fill sections 2-8 (and 9 if migration in scope)."
exit 0
