#!/usr/bin/env bash
# study-existing.sh — per-file deep comparison of target's existing setup vs pack equivalents.
#
# Solves the third bug: the agent runs REFRESH/REFINE/ENHANCE and only ADDS missing files.
# It does NOT compare existing files against pack equivalents to decide what should be
# ENHANCED (deepen/improve), ALIGNED (re-anchor to project), or DELETED (deprecated).
#
# This script does the comparison in shell, applies Appendix C merge matrix
# deterministically, and writes a proposal report. Phase 4 must consume the proposals.
#
# Usage:
#   study-existing.sh <target-repo> [pack1 pack2 ...]
#
# Output: <target>/.claude/_study-existing-report.md
# Properties: deterministic; idempotent; read-only on the target's actual artifacts.

set -euo pipefail
export LC_ALL=C

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKS_ROOT="$REPO_ROOT/templates/packs"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <target-repo> [pack1 pack2 ...]" >&2
  exit 2
fi

TARGET="$1"; shift
[[ -d "$TARGET" ]] || { echo "ERR: target not found: $TARGET" >&2; exit 1; }

REPORT="$TARGET/.claude/_study-existing-report.md"
mkdir -p "$(dirname "$REPORT")"

PACKS=("$@")
if [[ ${#PACKS[@]} -eq 0 ]]; then
  # Auto-detect installed packs from target's codebase-profile.md if present.
  # Fall back to scanning ALL packs (so the report is never empty for projects
  # that don't have a tracks_selected line — the historic bug).
  if [[ -f "$TARGET/.claude/codebase-profile.md" ]]; then
    while IFS= read -r p; do
      [[ -n "$p" ]] && PACKS+=("$p")
    done < <(grep -E '^[[:space:]]*-?[[:space:]]*track:' "$TARGET/.claude/codebase-profile.md" 2>/dev/null \
             | sed -E 's/.*track:[[:space:]]+([a-z0-9-]+).*/\1/' | sort -u)
  fi
  if [[ ${#PACKS[@]} -eq 0 ]]; then
    # No tracks declared — scan ALL packs. The user's project may have
    # commands/agents from packs that aren't recorded in the profile.
    # Try find first; some sandboxes restrict find traversal even when ls
    # works, so fall back to a bash glob if find returns nothing.
    while IFS= read -r d; do
      name="$(basename "$d")"
      [[ "$name" == _* ]] && continue
      PACKS+=("$name")
    done < <(find "$PACKS_ROOT" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)
    if [[ ${#PACKS[@]} -eq 0 ]]; then
      for d in "$PACKS_ROOT"/*/; do
        [[ -d "$d" ]] || continue
        name="$(basename "$d")"
        [[ "$name" == _* ]] && continue
        [[ "$name" == "*" ]] && continue
        PACKS+=("$name")
      done
    fi
  fi
fi
# bash 3.2 (macOS default) treats `${arr[*]}` on an empty array as unbound under
# set -u — guard the trace line so it never crashes the preflight.
if [[ ${#PACKS[@]} -gt 0 ]]; then
  echo "Scanning packs: ${PACKS[*]}" >&2
else
  echo "Scanning packs: (none — neither codebase-profile track: lines nor $PACKS_ROOT scan yielded packs)" >&2
  echo "ERR: cannot proceed with zero packs. Pass packs as args, or check $PACKS_ROOT exists and is readable." >&2
  exit 1
fi

target_dir_for_kind() {
  case "$1" in
    commands)    echo "$TARGET/.claude/commands" ;;
    agents)      echo "$TARGET/.claude/agents" ;;
    skills)      echo "$TARGET/.claude/skills" ;;
    rules)       echo "$TARGET/.claude/rules" ;;
    ai-patterns) echo "$TARGET/ai/patterns" ;;
    *)           echo "$TARGET/.claude/$1" ;;
  esac
}

# Appendix C decision based on size ratio (target/pack) + byte-identity check.
# Codifies "Same name overlap" rules in shell so the agent can't override.
decide() {
  local target_path="$1" pack_path="$2"
  local target_size pack_size
  target_size=$(wc -l < "$target_path" | tr -d ' ')
  pack_size=$(wc -l < "$pack_path" | tr -d ' ')

  if [[ "$pack_size" -eq 0 ]]; then echo "ERROR_DIVZERO"; return; fi

  # Byte-identical = no work needed (Phase 4.6 will still anchor project-specific block separately)
  if cmp -s "$target_path" "$pack_path"; then
    echo "IDENTICAL-NO-OP"
    return
  fi

  local ratio=$(( target_size * 100 / pack_size ))

  if [[ $ratio -ge 200 ]]; then
    echo "KEEP-OURS-DEEP"
  elif [[ $ratio -ge 130 ]]; then
    echo "KEEP-OURS-PLUS-INJECT"
  elif [[ $ratio -ge 70 ]]; then
    echo "MERGE"
  elif [[ $ratio -ge 50 ]]; then
    echo "KEEP-OURS-ADD-SIDE-DOC"
  else
    echo "REPLACE-OR-ENHANCE"
  fi
}

# ---------- Build report ----------
{
  printf '# Study-existing report — %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'Target: `%s`\n\n' "$TARGET"
  printf 'Generated by: scripts/study-existing.sh\n\n'
  printf '> **MANDATORY for REFRESH / REFINE / ENHANCE.** Per-file decisions derived from Appendix C merge matrix. Phase 4 MUST address every row marked REPLACE-OR-ENHANCE / KEEP-OURS-PLUS-INJECT / MERGE before declaring success. Phase 5 audit FAILS the run if any actionable row was silently ignored.\n\n'
  printf -- '---\n\n'

  total_act=0
  total_keep=0
  total_missing=0
  total_orphan=0

  for pack in "${PACKS[@]}"; do
    pack_dir="$PACKS_ROOT/$pack"
    [[ -d "$pack_dir" ]] || continue

    pack_section=""
    pack_actionable=0

    for kind in commands agents skills rules ai-patterns; do
      kind_dir="$pack_dir/$kind"
      [[ -d "$kind_dir" ]] || continue

      tgt_dir="$(target_dir_for_kind "$kind")"
      [[ -d "$tgt_dir" ]] || continue

      kind_rows=""
      while IFS= read -r src; do
        base="$(basename "$src")"
        [[ "$base" == _* ]] && continue
        tgt="$tgt_dir/$base"

        if [[ -f "$tgt" ]]; then
          src_lines=$(wc -l < "$src" | tr -d ' ')
          tgt_lines=$(wc -l < "$tgt" | tr -d ' ')
          decision=$(decide "$tgt" "$src")
          kind_rows+=$'\n'"  - \`$base\` — target $tgt_lines / pack $src_lines lines → **$decision**"

          case "$decision" in
            REPLACE-OR-ENHANCE|KEEP-OURS-PLUS-INJECT|MERGE)
              pack_actionable=$(( pack_actionable + 1 ))
              total_act=$(( total_act + 1 ))
              ;;
            *)
              total_keep=$(( total_keep + 1 ))
              ;;
          esac
        else
          kind_rows+=$'\n'"  - \`$base\` — target MISSING / pack $(wc -l < "$src" | tr -d ' ') lines → **ADD**"
          pack_actionable=$(( pack_actionable + 1 ))
          total_missing=$(( total_missing + 1 ))
        fi
      done < <(find "$kind_dir" -maxdepth 1 -name '*.md' -not -name '_*' | sort)

      # Reverse: target files NOT in pack — orphans (project-specific or deprecated upstream)
      while IFS= read -r tgtf; do
        base="$(basename "$tgtf")"
        [[ "$base" == _* ]] && continue
        if [[ ! -f "$kind_dir/$base" ]]; then
          kind_rows+=$'\n'"  - \`$base\` — target-only (not in pack) → **REVIEW: project-specific keeper OR deprecated upstream**"
          total_orphan=$(( total_orphan + 1 ))
        fi
      done < <(find "$tgt_dir" -maxdepth 1 -name '*.md' -not -name '_*' 2>/dev/null | sort)

      [[ -n "$kind_rows" ]] && pack_section+=$'\n\n### '"$kind"$''$kind_rows
    done

    if [[ -n "$pack_section" ]]; then
      printf '## %s' "$pack"
      printf '%b' "$pack_section"
      printf '\n\nactionable in this pack: **%d**\n\n---\n\n' "$pack_actionable"
    fi
  done

  printf '## Decision legend\n\n'
  cat <<'LEGEND'
* ADD — file in pack but not target. Phase 4.2 must copy.
* IDENTICAL-NO-OP — target byte-identical to pack. No structural action; Phase 4.6 still anchors project-specific block.
* REPLACE-OR-ENHANCE — target ≤ 50% of pack size. Stub or shallow; replace with pack OR rewrite to pack depth.
* KEEP-OURS-PLUS-INJECT — target deeper but missing project-specific anchor. Phase 4.6 must inject anchor section into target.
* MERGE — sizes comparable; real per-section merge required.
* KEEP-OURS-ADD-SIDE-DOC — target slightly shallower; keep target, add pack as side-doc with different name.
* KEEP-OURS-DEEP — target ≥ 2× pack size; pack adds nothing. No action.
* REVIEW — file in target but NOT in pack. Could be project-specific (keep) or deprecated upstream (consider deleting). Human judgment required.
LEGEND

  printf '\n## Summary\n\n'
  printf 'Files with action needed: **%d**\n' "$(( total_act + total_missing ))"
  printf '  ADD (missing): %d\n' "$total_missing"
  printf '  ENHANCE / MERGE / INJECT: %d\n' "$total_act"
  printf 'Files to keep as-is: %d\n' "$total_keep"
  printf 'Files to review (orphans): %d\n\n' "$total_orphan"

  if [[ $(( total_act + total_missing )) -eq 0 && "$total_orphan" -eq 0 ]]; then
    printf 'No actionable items. Setup is converged.\n'
  else
    printf '⚠ Phase 4 MUST address every actionable row. Phase 5 audit refuses success otherwise.\n'
  fi
} > "$REPORT"

echo "Study report written: $REPORT"
echo "Actionable: $(( total_act + total_missing )) | Keep: $total_keep | Orphans: $total_orphan"
exit 0
