#!/usr/bin/env bash
# verify-cheatsheet.sh — fail if docs/CHEATSHEET.md has drifted from the command files.
#
# The cheat sheet is generated by scripts/gen-cheatsheet.py from every */commands/*.md
# (name + frontmatter description + H1 signature + flags). This gate re-derives it and
# fails (CI-blocking) if the committed file is stale — i.e. a command was added, renamed,
# or had its description/flags changed without re-running the generator. Fix with:
#   python3 scripts/gen-cheatsheet.py
#
# Usage:  verify-cheatsheet.sh [--repo-root=<dir>]
# Exit:   1 if stale (or python3 missing), 0 if in sync.

set -euo pipefail
export LC_ALL=C

# Symlink-resolved: ~/.claude/scripts/<name> links into this repo (see CONTRIBUTING
# § "Scripts run from two places"). Gate: lint-setup-contracts.sh Rule 10.
_ss="${BASH_SOURCE[0]}"
while [ -L "$_ss" ]; do _sd="$(cd -P "$(dirname "$_ss")" && pwd)"; _ss="$(readlink "$_ss")"; case "$_ss" in /*) ;; *) _ss="$_sd/$_ss" ;; esac; done
REPO_ROOT="$(cd -P "$(dirname "$_ss")/.." && pwd)"; unset _ss _sd
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-root=*) REPO_ROOT="${1#*=}"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
cd "$REPO_ROOT" || exit 1

if ! command -v python3 >/dev/null 2>&1; then
  echo "FAIL  python3 not found — required to verify docs/CHEATSHEET.md" >&2
  exit 1
fi

exec python3 scripts/gen-cheatsheet.py --check
