#!/usr/bin/env bash
# verify-pack-matrix.sh — fail if assets/pack-matrix.svg has drifted from the pack corpus.
#
# The matrix is generated by scripts/gen-pack-matrix.py from templates/packs/* (agents,
# skills, commands, rules measured on disk; always-applied flag + summary from
# templates/packs/_registry.md). This gate re-renders it and fails (CI-blocking) if the
# committed SVG is stale — i.e. a pack was added, renamed or removed, or its artifact
# counts changed, without re-running the generator. Fix with:
#   python3 scripts/gen-pack-matrix.py
#
# Why it exists: the SVG was hand-authored and silently trailed the filesystem — it still
# read "twenty packs" three packs after data-engineering, finops and product landed, and
# its per-pack agent counts had drifted too. README prose is NOT covered here; see
# scripts/verify-readme-stats.sh.
#
# Usage:  verify-pack-matrix.sh [--repo-root=<dir>]
# Exit:   1 if stale (or python3 missing), 0 if in sync.

set -euo pipefail
export LC_ALL=C

# SELF_ROOT is where the generator lives; REPO_ROOT is the tree being checked. They differ
# when tests/validators/ points this at a fixture, so the generator is always addressed
# absolutely and the target is passed through as --repo-root.
SELF_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$SELF_ROOT"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-root=*) REPO_ROOT="${1#*=}"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -d "$REPO_ROOT" ] || { echo "FAIL  --repo-root does not exist: $REPO_ROOT" >&2; exit 1; }

if ! command -v python3 >/dev/null 2>&1; then
  echo "FAIL  python3 not found — required to verify assets/pack-matrix.svg" >&2
  exit 1
fi

exec python3 "$SELF_ROOT/scripts/gen-pack-matrix.py" --check --repo-root="$REPO_ROOT"
